scan-robot:
    stage: test
    image: fedora:31
    artifacts:
        when: always
        paths:
            - ./results
        expire_in: 1 week
    before_script:
        - cat /etc/*-release
        - dnf upgrade -y >/dev/null && echo OK
        - dnf install -y python37 >/dev/null && echo OK
        - dnf module install -y nodejs:14 >/dev/null && echo OK
        - dnf install -y fedora-workstation-repositories >/dev/null && echo OK
        - dnf install -y 'dnf-command(config-manager)' >/dev/null && echo OK
        - pip3 install robotframework robotframework-browser robotframework-faker | grep "Successfully installed"
        - rfbrowser init
        - dfn install -y libatk-1.0.so.0 libatk-bridge-2.0.so.0 libxkbcommon.so.0 libXcomposite.so.1 libXdamage.so.1 libXfixes.so.3 libXrandr.so.2 libgbm.so.1 libgtk-3.so.0 libgdk-3.so.0 libpango-1.0.so.0 libcairo.so.2 libatspi.so.0 libxshmfence.so.1
        - python --version
        - node --version
        - dnf upgrade -y >/dev/null && echo OK
    script:
        - robot -d ./results tests
    tags:
    - linux
    - docker-runner